[package]
name = "xabe-engine"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
xabe-asr.workspace = true
xabe-chat.workspace = true
xabe-audio.workspace = true
xabe-cosy.workspace = true
xabe-serve.workspace = true
xabe-vad.workspace = true
xabe-translate.workspace = true
xabe-tts.workspace = true
xabe-vits.workspace = true
clap.workspace = true
thiserror.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
tokio.workspace = true
base64.workspace = true

[[bin]]
name = "xabe-engine"
path = "src/main.rs"

[[bin]]
name = "xabe-asr-bench"
path = "src/bin/asr_bench.rs"
