[package]
name = "xabe-cosy"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
xabe-cuda.workspace = true
xabe-dsp.workspace = true
xabe-st.workspace = true
regex.workspace = true
rustc-hash.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tracing.workspace = true

[dev-dependencies]
serde.workspace = true
xabe-audio.workspace = true
