[package]
name = "xabe-tts"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
xabe-dsp.workspace = true
xabe-st.workspace = true
xabe-vits.workspace = true
clap.workspace = true
thiserror.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true

[dev-dependencies]
xabe-golden.workspace = true

[[bin]]
name = "xabe-tts"
path = "src/main.rs"
